select * from customer; 

select sum(purchase_amount) as total_revenue,gender from customer --total revenuse generated by gender
GROUP BY gender;

-- discount used but spend more than average purchase
select customer_id, purchase_amount
from customer
WHERE discount_applied = 'Yes' and
purchase_amount >= (select avg(purchase_amount) from customer);


-- top 5 products with highest average review rating
SELECT top 5 item_purchased, round(avg(review_rating),2) as "Average Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc


-- avg purchase amounts between standard and express shipping
select round(avg(purchase_amount),2) as "Average purchase amount", shipping_type from customer
WHERE shipping_type in( 'Standard','Express')
GROUP By shipping_type;

-- average spend and total revenue between subscribers and non-subscribers

select subscription_status,count(customer_id) as "total customers", round(AVG(purchase_amount),2) as "Average Spend", round(SUM(purchase_amount),2) as "Total revenue" 
from customer
GROUP by subscription_status;

-- 5 products with highest percentge of purchase with discounts

select top 5 item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc;

-- segment customers into new, returning, loyal based on their total number of previous purchase and show the count
with customer_type as(
	select customer_id, previous_purchases,
	case 
		when previous_purchases = 1 then 'New'
		when previous_purchases BETWEEN 2 AND 10 then 'Returning'
		else 'Loyal'
		end as customer_segment
from customer
) 
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


-- top 3 most purchased products within each category
with category_type as (
select category, item_purchased, count(customer_id) as total_oders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank, category,item_purchased, total_oders 
from category_type
where item_rank <=3



-- are customers who are repeat buyers (more than 5 ) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- revenue contribution of each age group
select age_groups, sum(purchase_amount) as total_revenue
from customer
group by age_groups
order by total_revenue desc